num_1 =int(input("Enter first number:"))
num_2 =int(input("Enter second number:"))
print(f"Addition: {num_1+num_2}")
print(f"Subtraction:{num_1-num_2}")
print(f"Multiplication:{num_1*num_2}")
print(f"Division:{num_1%num_2}")